spring:
  application:
      name: AstonIntensiveHibernate
  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    driver-class-name: org.postgresql.Driver

